### ISSUE TITLE
Favicon fails to render in production

### ISSUE THREAD

**Issue by pranav7** [LightningFF/lightning#28]
Here's a link to the error: https://getcadet.slack.com/archives/C79HBGSN8/p1623157175001100

**Error: `The asset "lightning/favicon" is not present in the asset pipeline.`**

```
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:84:in `compute_asset_path'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/actionview-5.2.4.4/lib/action_view/helpers/asset_url_helper.rb:200:in `asset_path'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/actionview-5.2.4.4/lib/action_view/helpers/asset_url_helper.rb:375:in `image_path'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/actionview-5.2.4.4/lib/action_view/helpers/asset_tag_helper.rb:230:in `favicon_link_tag'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/bundler/gems/lightning-3634658ff0a3/app/views/layouts/lightning/application.html.erb:8:in `__home_rails_apps_cadet_app_shared_bundle_ruby_______bundler_gems_lightning________ff_a__app_views_layouts_lightning_application_html_erb__3896635606218985059_73300440'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/actionview-5.2.4.4/lib/action_view/template.rb:159:in `block in render'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:170:in `instrument'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/actionview-5.2.4.4/lib/action_view/template.rb:354:in `instrument_render_template'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/actionview-5.2.4.4/lib/action_view/template.rb:157:in `render'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/actionview-5.2.4.4/lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
```

**Comment by pranav7** [comment]
I think the production build on Cadet is not picking up fresh code from `main` branch on lightning, we might have to figure out a way to reload fresh code.
